// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/apple-directions/AuroraDepth.tsx": () => import("../components/mockups/apple-directions/AuroraDepth.tsx"),
  "./components/mockups/apple-directions/FrostedGlass.tsx": () => import("../components/mockups/apple-directions/FrostedGlass.tsx"),
  "./components/mockups/apple-directions/UltraMinimal.tsx": () => import("../components/mockups/apple-directions/UltraMinimal.tsx")
};
